### PR TITLE
Update with Tailwind css

### PR DESCRIPTION
**Pull request by rissajackson**
Figma: https://www.figma.com/file/FQ4UWYkiRmjiqokTvlxxhv/Laravel-Valet?node-id=0%3A1

Screen Shot 2021-07-06 at 1 55 30 PM

Valet:
Screen Shot 2021-07-06 at 2 00 52 PM

Particularly proud of figuring out how to get the bullet points purple for the links:
Screen Shot 2021-07-07 at 10 13 59 AM

In the routes/web.php file I added:
'valet-fallback', 'tightendotco', 'confomo'
So they could show up as Parked. However, I didn't push these changes in case you did not want them in the repo.
Screen Shot 2021-07-06 at 1 56 46 PM

### CODE REVIEW

**Comment by mattstauffer** [comment]
Great work! I've added some notes here:

image

**Comment by mattstauffer** [comment]
@rissajackson Please just update the screenshot and tag me for review whenever you're ready for me to take another look. Thanks!

**Comment by rissajackson** [comment]
Current screenshot Web:
Screen Shot 2021-07-07 at 2 34 43 PM

Figma:
Screen Shot 2021-07-07 at 2 36 33 PM

**Comment by rissajackson** [comment]
Finished adding in all the PR Feedback.

**Pull request merged**
